### ISSUE TITLE
not available for R version 3.5.1

### ISSUE THREAD

**Issue by christinaotto** [stefanocoretta/rticulate#2]
Hi,
I have trouble to install the package "tidymv" and "rticulate". I get the following warning:

 ‘tidymv’ ist nicht verfügbar (for R version 3.5.1) 

I tried to install a earlier R version and I tried to install it manually from the Zip-archive but it didn't work either.
What am I doing wrong?

Christina

**Comment by stefanocoretta** [comment]
Hi! 👋 Since you closed the issue, I guess you solved. Anyway, if it is of help, both `tidymv` and `rticulate`  should work with R v3.5.1. 😊

**Comment by christinaotto** [comment]
HI,

yes. I tried around and after installing the devtools package, I was  
able to install both packages using your code. I don't know why it's  
not possible to install it the way, I usually install packages (with  
the install.packages command).

But anyway, it works just fine. Thank you very much!

Christina



Zitat von Stefano Coretta <notifications@github.com>:

> Hi! 👋 Since you closed the issue, I guess you solved. Anyway, if it  
> is of help, both `tidymv` and `rticulate`  should work with R  
> v3.5.1. 😊
>
> --
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/stefanocoretta/rticulate/issues/2#issuecomment-411690029



-- 
Christina Otto, M.A.
Friedrich-Schiller-Universität Jena
Institut für Germanistische Sprachwissenschaft
Professur für Sprechwissenschaft und Phonetik
Fürstengraben 30
07743 JENA

Tel.: 03641/944334
Raum: 102 A

**Comment by stefanocoretta** [comment]
You could not install the packages using `install.packages()` because this command only works with packages that are on [CRAN](https://cran.r-project.org), and for now `tidymv` and `rticulate` are available only from GitHub. That's why you rather need to use `devtools::install_github()`. Hope this clarifies!
